"""Adicionando estado e cidade à oficina

Revision ID: 0224940e9820
Revises: 
Create Date: 2025-01-23 15:12:57.608495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0224940e9820'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oficina', sa.Column('estado', sa.String(length=2), nullable=False, server_default="XX"))
    op.add_column('oficina', sa.Column('cidade', sa.String(length=100), nullable=False, server_default="Cidade Padrão"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oficina', 'cidade')
    op.drop_column('oficina', 'estado')
    # ### end Alembic commands ###
