"""Adicionado campo palavras_chave em Oficina

Revision ID: 3c588beb375a
Revises: b432f1828d5c
Create Date: 2025-01-24 13:35:04.623715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c588beb375a'
down_revision = 'b432f1828d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('palavras_chave', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.drop_column('palavras_chave')

    # ### end Alembic commands ###
