"""Adiciona colunas palavra_chave_manha e palavra_chave_tarde

Revision ID: 5294d5c540e1
Revises: 3c588beb375a
Create Date: 2025-01-24 14:49:40.466639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5294d5c540e1'
down_revision = '3c588beb375a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.drop_column('palavras_chave')

    with op.batch_alter_table('oficina_dia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('palavra_chave_manha', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('palavra_chave_tarde', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina_dia', schema=None) as batch_op:
        batch_op.drop_column('palavra_chave_tarde')
        batch_op.drop_column('palavra_chave_manha')

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('palavras_chave', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
