"""Adicionando campo QR Code opcional em Oficina

Revision ID: 6c75026e1492
Revises: 0224940e9820
Create Date: 2025-01-23 23:56:39.553315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c75026e1492'
down_revision = '0224940e9820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oficina', sa.Column('qr_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oficina', 'qr_code')
    # ### end Alembic commands ###
